BBBatScale/core/urls.py
from core.views import (
    api,
    api_token,
    groups,
    home,
    home_room,
    import_export,
    meetings,
    personal_room,
    recordings,
    room_configurations,
    rooms,
    scheduling_strategies,
    servers,
    settings,
    slides,
    statistics,
    tenants,
    users,
)
from django.conf import settings as django_settings
from django.urls import path
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path("jsi18n", JavaScriptCatalog.as_view(packages=["core"]), name="core_javascript_catalog"),
    path("api/callback/bbb/", api.callback_bbb, name="callback_bbb"),
    path("api/recording/postporocessing/done/", api.recording_callback),
    path("api/user/delete", api.delete_user_callback),
    path("api/servers/registration", api.api_server_registration, name="api_server_registration"),
    path("api/servers/stats", api.api_sync_servers_stats, name="api_servers_stats"),
    path(
        "api/general-rooms",
        home.get_rooms,
        name="api_fetch_general_rooms",
    ),
    path("api/room/<int:room>/favorite", home.favorite, name="api_set_favorite"),
    path("api/personal-rooms", home.get_personal_rooms, name="api_fetch_personal_rooms"),
    path("api/home-rooms", home.get_home_rooms, name="api_fetch_home_rooms"),
    path("api/meetings", meetings.get_meetings, name="api_fetch_meetings"),
    path("api/users", users.get_users, name="api_fetch_users"),
    path("api/servers", servers.get_servers, name="api_fetch_servers"),
    path("api/tenants", tenants.get_tenants, name="api_fetch_tenants"),
    path("api/tokens", api_token.get_tokens, name="api_fetch_tokens"),
    path("api/groups", groups.get_groups, name="api_fetch_groups"),
    path("api/rooms", rooms.get_rooms, name="api_fetch_rooms"),
    path("api/recordings", recordings.get_recordings, name="api_fetch_recordings"),
    path(
        "api/schedulingstrategy",
        scheduling_strategies.get_scheduling_strategies,
        name="api_fetch_scheduling_strategies",
    ),
    path("servers/overview", servers.servers_overview, name="servers_overview"),
    path("rooms/overview", rooms.rooms_overview, name="rooms_overview"),
    path(
        "schedulingstrategies/overview",
        scheduling_strategies.scheduling_strategy_overview,
        name="scheduling_strategy_overview",
    ),
    path("rooms/configs/overview", room_configurations.room_config_overview, name="room_configs_overview"),
    path("server/create/", servers.server_create, name="server_create"),
    path("server/delete/<int:server>", servers.server_delete, name="server_delete"),
    path("server/update/<int:server>", servers.server_update, name="server_update"),
    path("servers/update/multiple", servers.server_multiple_state_update, name="server_multiple_state_update"),
    path("room/create/", rooms.room_create, name="room_create"),
    path("room/delete/<int:room>", rooms.room_delete, name="room_delete"),
    path("room/update/<int:room>", rooms.room_update, name="room_update"),
    path("room/reset/stucked/<int:room>", rooms.room_reset_stucked, name="room_reset_stucked"),
    path("home_room/update<int:home_room>", home_room.home_room_update, name="home_room_update"),
    path("personal_room/create", personal_room.personal_room_create, name="personal_room_create"),
    path("personal_room/update/<int:personal_room>", personal_room.personal_room_update, name="personal_room_update"),
    path("personal_room/delete/<int:personal_room>", personal_room.personal_room_delete, name="personal_room_delete"),
    path(
        "personal_rooms/change/owner/<int:owner>",
        personal_room.personal_room_batch_change_owner,
        name="personal_room_batch_change_owner",
    ),
    path("statistics", statistics.statistics, name="statistics"),
    path("importexport", import_export.import_export, name="import_export"),
    path("export/json", import_export.export_download_json, name="export_download_json"),
    path("export/csv", import_export.export_download_csv, name="export_download_csv"),
    path("import/json", import_export.import_upload_json, name="import_upload_json"),
    path("import/csv", import_export.import_upload_csv, name="import_upload_csv"),
    path("room/config/create/", room_configurations.room_config_create, name="room_config_create"),
    path("room/config/delete/<int:room_config>", room_configurations.room_config_delete, name="room_config_delete"),
    path("room/config/update/<int:room_config>", room_configurations.room_config_update, name="room_config_update"),
    path(
        "schedulingstrategy/create/",
        scheduling_strategies.scheduling_strategy_create,
        name="scheduling_strategy_create",
    ),
    path(
        "schedulingstrategy/delete/<int:scheduling_strategy>",
        scheduling_strategies.scheduling_strategy_delete,
        name="scheduling_strategy_delete",
    ),
    path(
        "schedulingstrategy/update/<int:scheduling_strategy>",
        scheduling_strategies.scheduling_strategy_update,
        name="scheduling_strategy_update",
    ),
    path(
        "schedulingstrategy/agentconfiguration/update/<int:scheduling_strategy>",
        scheduling_strategies.agent_configuration_update,
        name="agent_configuration_update",
    ),
    path("recordings/overview/", recordings.recordings_list, name="recordings_list"),
    path("recordings/update/<str:recording_id>", recordings.recording_update, name="recording_update"),
    path(
        "recording/mark/deletion/<str:recording_id>",
        recordings.recording_mark_for_deletion,
        name="recording_mark_for_deletion",
    ),
    path(
        "recording/unmark/deletion/<str:recording_id>",
        recordings.recording_unmark_for_deletion,
        name="recording_unmark_for_deletion",
    ),
    path(
        "recording/download/zip/<str:recording_id>",
        recordings.recording_download_zip_redirect,
        name="recording_download_zip_redirect",
    ),
    path(
        "recordings/change/owner/<int:owner>",
        recordings.recordings_batch_change_owner,
        name="recordings_batch_change_owner",
    ),
    path("users/overview/", users.users_overview, name="users_overview"),
    path("user/create/", users.user_create, name="user_create"),
    path("user/change/password/", users.user_change_password, name="change_password"),
    path("user/delete/<int:user>", users.user_delete, name="user_delete"),
    path("user/details/<int:user>", users.user_details, name="user_details"),
    path("user/update/<int:user>", users.user_update, name="user_update"),
    path("user/settings", users.user_settings, name="user_settings"),
    path("user/change/password/admin/<int:user>", users.user_change_password_admin, name="user_reset_password_admin"),
    path("groups/overview/", groups.groups_overview, name="groups_overview"),
    path("group/create/", groups.group_create, name="group_create"),
    path("group/delete/<int:group>", groups.group_delete, name="group_delete"),
    path("group/update/<int:group>", groups.group_update, name="group_update"),
    path("room/meeting/end/<int:room_pk>", rooms.force_end_meeting, name="force_end_meeting"),
    path("<slug:slug>/bigbluebutton/api/", api.bbb_initialization_request, name="bbb_api_initial_request"),
    path("<slug:slug>/bigbluebutton/api/join", api.bbb_api_join, name="bbb_api_join"),
    path("<slug:slug>/bigbluebutton/api/create", api.bbb_api_create, name="bbb_api_create"),
    path("<slug:slug>/bigbluebutton/api/getMeetingInfo", api.bbb_api_get_meeting_info, name="bbb_api_get_meeting_info"),
    path("<slug:slug>/bigbluebutton/api/getMeetings", api.bbb_api_get_meetings, name="bbb_api_get_meetings"),
    path(
        "<slug:slug>/bigbluebutton/api/isMeetingRunning",
        api.bbb_api_is_meeting_running,
        name="bbb_api_is_meeting_running",
    ),
    path("<slug:slug>/bigbluebutton/api/end", api.bbb_api_end, name="bbb_api_end"),
    path("<slug:slug>/bigbluebutton/api/getRecordings", api.bbb_api_get_recordings, name="bbb_api_get_recordings"),
    path(
        "<slug:slug>/bigbluebutton/api/publishRecordings",
        api.bbb_api_publish_recordings,
        name="bbb_api_publish_recordings",
    ),
    path(
        "<slug:slug>/bigbluebutton/api/updateRecordings",
        api.bbb_api_update_recordings,
        name="bbb_api_update_recordings",
    ),
    path(
        "<slug:slug>/bigbluebutton/api/deleteRecordings",
        api.bbb_api_delete_recordings,
        name="bbb_api_delete_recordings",
    ),
    path("settings", settings.GeneralParameterUpdateView.as_view(), name="update_general_parameter"),
    path(
        "settings/<int:pk>", settings.AdminGeneralParameterUpdateView.as_view(), name="admin_update_general_parameter"
    ),
    path("coowner/user/search", users.user_search_json, name="json_search_user"),
    path("tenants/overview/", tenants.tenant_overview, name="tenant_overview"),
    path("tenant/create/", tenants.tenant_create, name="tenant_create"),
    path("tenant/delete/<int:tenant>", tenants.tenant_delete, name="tenant_delete"),
    path("tenant/update/<int:tenant>", tenants.tenant_update, name="tenant_update"),
    path("token/overview/", api_token.token_overview, name="token_overview"),
    path("token/create/", api_token.token_create, name="token_create"),
    path("token/delete/<int:token>", api_token.token_delete, name="token_delete"),
    path("token/update/<int:token>", api_token.token_update, name="token_update"),
    path("meetings/overview/", meetings.meetings_overview, name="meeting_overview"),
    path("meeting/detail/<uuid:meeting_id>", meetings.meeting_detail, name="meeting_detail"),
]

if django_settings.BBBATSCALE_MEDIA_ENABLED:
    urlpatterns += [
        path("slides/overview/", slides.slides_overview, name="slides_overview"),
        path("slides/create/", slides.slides_create_update, name="slides_create"),
        path("slides/update/<int:slides_id>", slides.slides_create_update, name="slides_update"),

BBBatScale/support_chat/models.py
from __future__ import annotations

from typing import Any

from core.models import User
from core.utils import get_permission, has_tenant_based_perm
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.db import models, transaction
from django.db.models import F, Q
from django.utils.functional import SimpleLazyObject
from django.utils.translation import gettext_lazy as _


class SupportChatParameterManager(models.Manager):
    def load(self, tenant: Site) -> SupportChatParameter:
        return self.get_or_create(tenant=tenant)[0]


class SupportChatParameter(models.Model):
    tenant = models.OneToOneField(Site, on_delete=models.CASCADE)
    enabled = models.BooleanField(_("Enable Support Chat"), default=False)
    disable_chat_if_offline = models.BooleanField(_("Disable Support Chat if offline"), default=False)
    allow_supporter_to_inactivate_all = models.BooleanField(
        _("Allow supporter to inactivate all supporters"), default=False
    )
    message_max_length = models.IntegerField(_("Maximum message length"), default=255)

    objects = SupportChatParameterManager()


class Chat(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["owner", "tenant"], name="support_chat_chat_owner_tenant_unique")
        ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    tenant = models.ForeignKey(Site, on_delete=models.CASCADE, editable=False)
    support_active = models.PositiveIntegerField(default=0)
    unread_owner_messages = models.PositiveIntegerField(default=0)
    unread_support_messages = models.PositiveIntegerField(default=0)

    @property
    def is_support_active(self) -> bool:
        return self.support_active > 0


class ChatMessageManager(models.Manager):
    @transaction.atomic
    def create_and_update(
        self, chat: Chat, user: User, message: str, *args: Any, is_supporter: bool, **kwargs: Any
    ) -> ChatMessage:
        if is_supporter:
            chat.unread_support_messages = F("unread_support_messages") + 1
            chat.save(update_fields=["unread_support_messages"])
            chat.refresh_from_db(fields=["unread_support_messages"])
        else:
            chat.unread_owner_messages = F("unread_owner_messages") + 1
            chat.save(update_fields=["unread_owner_messages"])
            chat.refresh_from_db(fields=["unread_owner_messages"])
        return self.create(*args, chat=chat, user=user, message=message, **kwargs)


class ChatMessage(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, editable=False)
    message = models.TextField(editable=False)

    objects = ChatMessageManager()


class PreparedAnswer(models.Model):
    tenant = models.ForeignKey(Site, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()


class SupporterManager(models.Manager):
    def load(self, user: User, tenant: Site) -> Supporter:
        if not has_tenant_based_perm(user, "support_chat.support_users", tenant):
            raise PermissionDenied

        return self.get_or_create(user=user, tenant=tenant)[0]


# This can not be a class member of SupporterQuerySet since it would be evaluated before the Models are loaded,
# caused by the inspection of the Manager.from_queryset method.
_cached_support_users_permission = SimpleLazyObject(lambda: get_permission("support_chat.support_users"))


class SupporterQuerySet(models.QuerySet):
    def filter_support_eligible(self, tenant: Site) -> SupporterQuerySet:
        filter_is_superuser = Q(user__is_superuser=True)
        filter_user_in_tenant = Q(user__tenant=tenant)
        filter_user_is_staff = Q(user__is_staff=True)
        filter_user_has_user_perm = Q(user__user_permissions__in=[_cached_support_users_permission])
        filter_user_has_group_perm = Q(user__groups__permissions__in=[_cached_support_users_permission])

        filter_user_has_perm = filter_user_has_user_perm | filter_user_has_group_perm

        filter_user_has_tenant_based_perm = filter_user_in_tenant & (filter_user_is_staff | filter_user_has_perm)

        filter_is_support_eligible = filter_is_superuser | filter_user_has_tenant_based_perm

        return self.filter(filter_is_support_eligible, tenant=tenant)

    def filter_status_active(self, tenant: Site, status_active: bool) -> SupporterQuerySet:
        return self.filter_support_eligible(tenant).filter(is_status_active=status_active)


class Supporter(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "tenant"], name="support_chat_supporter_user_tenant_unique")
        ]
        permissions = [
            ("support_users", _("Can support users")),
        ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    tenant = models.ForeignKey(Site, on_delete=models.CASCADE, editable=False)
    is_status_active = models.BooleanField(
        _("Status active"),
        default=False,
        help_text=_("If enabled, the user could support other users in the support chat."),
    )

    objects = SupporterManager.from_queryset(SupporterQuerySet)()

    def __str__(self) -> str:
        return str(self.user)

BBBatScale/core/views/home_room.py
import logging

from core.feature_flag import Feature
from core.forms import HomeRoomForm
from core.models import HomeRoom
from core.utils import get_general_parameter, get_tenant, has_tenant_based_perm
from core.views import create_view_access_logging_message
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


@Feature.HomeRooms.is_enabled
@login_required
def home_room_update(request: HttpRequest, home_room: int) -> HttpResponse:
    logger.info(create_view_access_logging_message(request, home_room))
    tenant = get_tenant(request)
    general_parameter = get_general_parameter(request)
    instance = get_object_or_404(HomeRoom.objects_available.init(tenant, general_parameter), pk=home_room)

    if instance.owner != request.user and not has_tenant_based_perm(request.user, "core.change_homeroom", tenant):
        logger.warning("{} has tried to update home room of {}".format(request.user, instance.owner))
        raise PermissionDenied

    form = HomeRoomForm(
        request.POST or None,
        tenant=tenant,
        general_parameter=general_parameter,
        requesting_user=request.user,
        instance=instance,
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, _("Home room was updated successfully."))
        return redirect("home")
    return render(request, "home_rooms_update.html", {"form": form})

BBBatScale/core/templates/api_token_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load theme %}

{% block styles %}
    {% theme "multi_select" "stylesheet" %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'plugins/multi-select/js/jquery.multi-select.js' %}"></script>
    <script>
        jQuery(function () {
            jQuery('#id_tenants').multiSelect();
        });
    </script>
{% endblock scripts %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% translate "Create token" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/api_token_overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load core_tags %}

{% block scripts %}
    <script src="{% static "utilities/js/pagination.js" %}"></script>
    <script>
        /**
         * @typedef {Object} Token
         * @property {string} updateUrl
         * @property {string} deleteUrl
         * @property {string} apiUrl
         * @property {string} name
         * @property {string} secret
         * @property {Array<string>} tenants
         * @property {string} slug
         * @property {string|null} schedulingStrategy
         */

        window.addEventListener("load", function() {
            /**
             *
             * @param {URL} url
             * @param {number} page
             * @return {URL}
             */
            function setURLParameter(url, page) {
                url.searchParams.set("page", page.toFixed(0));

                return url;
            }

            const paginator = new Paginator({
                getUrl(page) {
                    return setURLParameter(getUrl("{% url "api_fetch_tokens" %}"), page).toString();
                },
                renderHead() {
                    const row = document.createElement("tr");

                    row.append(this.createTableHead("{% translate "Name" %}"));

                    row.append(this.createTableHead("{% translate "Secret" %}"));

                    row.append(this.createTableHead("{% translate "Url" %}"));

                    row.append(this.createTableHead("{% translate "Slug" %}"));

                    row.append(this.createTableHead("{% translate "Tenants" %}"));

                    row.append(this.createTableHead("{% translate "Scheduling Strategy" %}"));

                    const action = this.createTableHead("{% translate "Action" %}");
                    action.classList.add("text-right");
                    row.append(action);

                    return row;
                },
                /**
                 * @param {Token} token
                 * @return {HTMLTableRowElement}
                 */
                renderEntry(token) {
                    const row = document.createElement("tr");

                    const name = document.createElement("td");
                    name.innerText = token.name;
                    row.append(name);

                    const secrete = document.createElement("td");
                    row.append(secrete);

                    const secretGroup = document.createElement("div");
                    secretGroup.classList.add("input-group", "input-group-sm");
                    secrete.append(secretGroup);

                    const secretInput = document.createElement("input");
                    secretInput.type = "password";
                    secretInput.classList.add("form-control");
                    secretInput.value = token.secret;
                    secretGroup.append(secretInput);

                    const secreteInputAppend = document.createElement("span");
                    secreteInputAppend.classList.add("input-group-append");
                    secretGroup.append(secreteInputAppend);

                    const revealHideSecret = document.createElement("button");
                    revealHideSecret.classList.add("btn", "btn-secondary", "btn-flat");
                    revealHideSecret.type = "button";
                    revealHideSecret.title = "{% translate "Reveal secret" %}";
                    revealHideSecret.dataset.boundary = "viewport";
                    secreteInputAppend.append(revealHideSecret);

                    const revealPictogram = document.createElement("em");
                    revealPictogram.classList.add("fa", "fa-sm", "fa-eye");
                    revealHideSecret.append(revealPictogram);

                    revealHideSecret.addEventListener("click", () => {
                        if (secretInput.type === "password") {
                            secretInput.type = "text";
                            revealPictogram.classList.replace("fa-eye", "fa-eye-slash");
                        } else {
                            secretInput.type = "password";
                            revealPictogram.classList.replace("fa-eye-slash", "fa-eye");
                        }
                    });

                    const copySecret = document.createElement("button");
                    copySecret.type = "button";
                    copySecret.classList.add("btn", "btn-success", "btn-flat");
                    copySecret.title = "{% translate "Copy secret" %}";
                    copySecret.dataset.boundary = "viewport";
                    secreteInputAppend.append(copySecret);

                    copySecret.addEventListener("click", () => {
                        copyToClipboard(secretInput.value)
                            .then(() => toastr.success("{% translate "The secret has successfully been copied to the clipboard." %}"))
                            .catch(() => toastr.error("{% translate "Your Browser does not support copying to the clipboard." %}"));

                    });

                    const copyPictogram = document.createElement("em");
                    copyPictogram.classList.add("fa", "fa-sm", "fa-copy");
                    copySecret.append(copyPictogram);

                    const url = document.createElement("td");
                    url.innerText = getUrl(token.apiUrl).toString();
                    row.append(url);

                    const slug = document.createElement("td");
                    slug.innerText = token.slug;
                    row.append(slug);

                    const tenants = document.createElement("td");
                    tenants.innerText = token.tenants.join(", ");
                    row.append(tenants);

                    const schedulingStrategy = document.createElement("td");
                    schedulingStrategy.innerText = token.schedulingStrategy ?? "-";
                    row.append(schedulingStrategy);

                    const actionColumn = document.createElement("td");
                    row.append(actionColumn);

                    const action = document.createElement("div");
                    actionColumn.append(action);
                    action.classList.add("btn-group", "btn-group-sm", "float-right");

                    const updateLink = document.createElement("a");
                    updateLink.classList.add("btn", "btn-success");
                    updateLink.href = token.updateUrl;
                    updateLink.title = "{% translate "Edit" %}";
                    updateLink.dataset.boundary = "viewport";
                    action.append(updateLink);

                    const updateLinkIcon = document.createElement("em");
                    updateLinkIcon.classList.add("fas", "fa-pen");
                    updateLink.append(updateLinkIcon);

                    const deleteLink = document.createElement("button");
                    deleteLink.classList.add("btn", "btn-danger");
                    deleteLink.title = "{% translate "Delete" %}";
                    deleteLink.dataset.boundary = "viewport";
                    deleteLink.addEventListener("click", () => {
                        document.getElementById("delete_token").href = token.deleteUrl;
                        jQuery("#delete_token_modal").modal("toggle");
                    }, false);
                    action.append(deleteLink);

                    const deleteLinkIcon = document.createElement("em");
                    deleteLinkIcon.classList.add("fas", "fa-trash-alt");
                    deleteLink.append(deleteLinkIcon);

                    return row;
                },
                /**
                 * @param {number} page
                 * @param {number} pageCount
                 * @param {number} totalCount
                 * @param {Array<Token>} entries
                 */
                pageLoadedCallback(page, pageCount, totalCount, entries) {
                    document.getElementById("tokens-count-badge").innerText = totalCount.toFixed();

                    const url = new URL(window.location);
                    setURLParameter(url, page);
                    window.history.replaceState({}, "", url);
                }
            });
            document.getElementById("tokens-card-body").append(paginator.container);

            let _initialSearchParams = new URL(window.location).searchParams;

            paginator.loadPage(Number(_initialSearchParams.get("page") || 1));
        });
    </script>
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% translate "Token Overview" %}
                                <span id="tokens-count-badge" class="badge badge-pill badge-primary">0</span>
                            </h3>
                            <div class="card-tools">
                                <a class="btn btn-sm btn-default float-right" href="{% url "token_create" %}"
                                   title="{% translate "Create" %}">
                                    <em class="fas fa-plus"></em>
                                </a>
                            </div>
                        </div>
                        <div id="tokens-card-body" class="card-body">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block modals %}
    <div id="delete_token_modal" class="modal fade" tabindex="-1" role="dialog"
         aria-labelledby="CenterModalLabel"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="CenterModalLabel">{% translate "Delete token" %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    {% translate "Are you sure you want to delete the token?" %}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href="" id="delete_token">
                        {% translate "Delete" %}
                    </a>
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">
                        {% translate "Cancel" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

BBBatScale/core/templates/batch_owner_change_form.html
{% extends "base.html" %}
{% load tenant_based_permission %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load theme %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
    <script>
        jQuery(function () {
            $("#id_owner").select2({
                theme: 'bootstrap4',
                minimumInputLength: 3,
                ajax: {
                    url: "{% url "json_search_user" %}",
                    processResults: function (data) {
                        let data_arr = [];
                        data["users"].forEach((user) => {
                            data_arr.push(
                                {
                                    id: user.id,
                                    text: user.display_name
                                }
                            )
                        });
                        let result = {
                            results: data_arr
                        };

                        return result;
                    }
                }
            });
        });
    </script>
{% endblock scripts %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{ title }}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}